### ISSUE TITLE
question:  CustomTaskQueue类里面的offer方法 里面if判断逻辑是？

### ISSUE THREAD

**Issue by rockeywang** [chenmudu/Tomcat8-Source-Read#31]
org.chenchen.customer.queue.CustomTaskQueue

offer方法
if(parentExecutor.getPoolSize() < parentExecutor.getMaximumPoolSize()) {
            return false;
  }
该代码判断逻辑是？

**Comment by chenmudu** [comment]
详见：java.util.concurrent.ThreadPoolExecutor#execute  1371行if判断。当前JDK版本为：jdk1.8.0_171。
`if (isRunning(c) && workQueue.offer(command)) `
在此逻辑下：改写线程池的入队逻辑，强制在未达到最大线程数之前(当前线程数已大于核心线程数)，优先创建线程而不是优先进入队列。
[点击查看详情](https://github.com/chenmudu/Tomcat8-Source-Read/blob/master/common-doc/doc/2-custom-executor.md)

**Comment by rockeywang** [comment]
Thank you!
